---
- name: test
  hosts: all
  tasks:
    - name: ping
      win_ping:
    - name: service
      win_service:
        name: FLEXlm License Manager
    - name: windows update
      win_updates:
        category_names:
        - SecurityUpdates
        state: installed
      register: update_result
    - name: debug
      debug:
        msg: "{{ update_result }}"
