---
- name: test
  hosts: all
  tasks:
    - name: ping
      win_ping:
    - name: service
      win_service:
        name: FLEXlm License Manager
    - name:  windows update
      win_update:
        category_names:
          - SecurityUpdates
