---
- name: test
  hosts: all
  tasks:
    - name: ping
      win_ping:
    - name: service
      win_service:
        name: FLEXlm License Manager
    - name: windows update
      win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        state: installed
#        reboot: yes
#        reboot_timeout: 1800
      register: update_result
    - name: debug
      debug: 
        var: update_result
        verbosity: 0
